import { notFound } from "next/navigation";
import people from "../../data/people.json";
import { profileSummaries } from "../../data/content";
import { Page, ImageBlock } from "../../components/Content";
type Props={params:Promise<{slug:string}>};
export async function generateMetadata({params}:Props){const {slug}=await params;return {title:`${people.find(p=>p.slug===slug)?.name??"Member"} | Kanatzidis Research Group`};}
export default async function Profile({params}:Props){const {slug}=await params;const p=people.find(p=>p.slug===slug);if(!p)notFound();return <Page active="people" eyebrow="People" title={p.name} description={p.category}><section className="section"><div className="shell profile-grid"><aside><ImageBlock label={`${p.name} portrait`} className="portrait-block"/>{p.email&&<a className="profile-email" href={`mailto:${p.email}`}>{p.email}</a>}{p.office&&<p>Office: {p.office}</p>}<a className="source-link" href={p.source}>{p.profileAvailable?"Original profile":"Original group directory"} ↗</a></aside><div><p className="eyebrow dark">Research & background</p><h2>{p.area||p.category}</h2>{profileSummaries[p.slug]&&<p className="body-copy">{profileSummaries[p.slug]}</p>}{!p.profileAvailable&&<p className="source-note">{p.slug==='xiuquan-zhou'?"Listed at Argonne National Laboratory in the original group directory.":"The original directory lists this member, but the linked biography is unavailable."}</p>}{p.education&&<><h3 className="subheading">Education & appointments</h3><p className="education-text">{p.education}</p></>}{p.note&&<p className="source-note">{p.note}</p>}<div className="profile-actions"><a className="text-link dark-link" href="/kanatzidis-demo/people">← Group directory</a><a className="text-link dark-link" href="/kanatzidis-demo/research">Explore our research →</a></div></div></div></section></Page>}

export function generateStaticParams(){return people.map(p=>({slug:p.slug}));}
