import { NewsSpotlight } from "./components/NewsSpotlight";
import { LatestNews } from "./components/NewsTimeline";
import { ResearchImage } from "./components/ResearchImage";
import { SiteFooter } from "./components/SiteFooter";
import { SiteHeader } from "./components/SiteHeader";
import { ImageBlock } from "./components/Content";
import { GroupGallery } from "./components/GroupGallery";
import { ResearchHighlights } from "./components/ResearchHighlights";
import { research } from "./data/content";
export default function Home(){return <><SiteHeader/><main id="main-content">
<section className="hero" id="top"><div className="shell hero-grid"><div className="hero-copy"><p className="eyebrow"><span aria-hidden="true"/>Solid-state inorganic chemistry</p><h1>Designing and discovering materials for <em>energy, light and sensing.</em></h1><p className="hero-lede">At Northwestern, we discover and design inorganic materials—from thermoelectric semiconductors to halide perovskites and radiation detectors.</p><div className="hero-actions"><a className="button button-primary" href="/kanatzidis-demo/research">Explore our research <span aria-hidden="true">↘</span></a><a className="text-link" href="/kanatzidis-demo/people">Meet the group <span aria-hidden="true">→</span></a></div></div><div className="hero-community"><figure className="hero-group-photo"><a href="#group-photos" aria-label="Explore group photos from 1993 to 2026"><img src="/kanatzidis-demo/images/group/2026.webp" alt="The Kanatzidis Group gathered outside the Technological Institute in 2026" width="1800" height="1275" fetchPriority="high"/></a><figcaption><span>Kanatzidis Group · 2026</span><a href="#group-photos">Through the years ↘</a></figcaption></figure><div className="group-identity"><img src="/kanatzidis-demo/images/kanatzidis-logo.webp" alt="Kanatzidis Group logo" width="1200" height="900"/><div><span>Our motto</span><blockquote>“Everything is made<br/>of something...”</blockquote></div></div></div></div><div className="shell focus-strip" aria-label="Research focus areas"><span className="focus-label">Our focus</span><a href="/kanatzidis-demo/research/exploratory-synthesis">Chalcogenides</a><a href="/kanatzidis-demo/research/thermoelectrics">Thermoelectrics</a><a href="/kanatzidis-demo/research/radiation-detection">Radiation detection</a><a href="/kanatzidis-demo/research/perovskites">Perovskites</a></div></section>
<aside className="home-meeting" aria-label="Group meeting"><div className="shell home-meeting-inner"><div className="meeting-day" aria-hidden="true"><span>EVERY</span><strong>MON</strong></div><div className="home-meeting-title"><p>Ideas, experiments & discussion</p><h2>Group Meeting</h2></div><div className="home-meeting-details"><strong>Mondays · 3:00 PM</strong><span>Tech K242 · Evanston time</span><small>See the schedule for exceptions.</small></div><a className="button" href="/kanatzidis-demo/meetings">View meeting schedule <span aria-hidden="true">→</span></a></div></aside>
<section className="section research-section" id="research"><div className="shell"><div className="section-heading split-heading"><div><p className="eyebrow dark"><span aria-hidden="true"/>Research directions</p><h2>Discovering and designing functional materials.</h2></div><p>Explore our work in materials synthesis, energy conversion, radiation detection and optoelectronics.</p></div><div className="research-grid">{research.map((r,i)=><a className={`research-card ${r.tone}`} href={`/kanatzidis-demo/research/${r.slug}`} key={r.slug}><ResearchImage slug={r.slug === "thermoelectrics" ? "thermoelectrics-snse-2014" : r.slug}/><div className="card-topline"><span>0{i+1}</span><span className="card-arrow" aria-hidden="true">↗</span></div><div>{r.subtitle && <p>{r.subtitle}</p>}<h3>{r.title}</h3><p className="card-description">{r.summary}</p></div></a>)}</div><div className="home-research-more"><a className="text-link dark-link" href="/kanatzidis-demo/research">Explore all research directions →</a></div></div></section>
<section className="section home-papers" id="publications"><div className="shell"><div className="section-heading news-heading"><div><p className="eyebrow dark"><span aria-hidden="true"/>Research highlights</p><h2>Recent work, at a glance.</h2></div><a className="text-link dark-link" href="/kanatzidis-demo/publications">Publication archive →</a></div><ResearchHighlights/></div></section>
<section className="section approach-section compact-approach" id="approach"><div className="shell"><div className="approach-heading"><div><p className="eyebrow light">How we work</p><h2>From synthesis to understanding.</h2></div><a className="text-link" href="/kanatzidis-demo/resources">Explore the laboratory →</a></div><ol className="method-steps"><li><span>01</span><h3>Synthesize</h3><p>Explore compositions and grow new crystals.</p></li><li><span>02</span><h3>Understand</h3><p>Connect crystal structure with physical properties.</p></li><li><span>03</span><h3>Refine</h3><p>Use what we learn to guide the next experiment.</p></li></ol></div></section>
<section className="section people-section" id="people"><div className="shell people-grid"><GroupGallery/><div className="people-copy"><p className="eyebrow dark"><span aria-hidden="true"/>Our group</p><h2>The people behind the discoveries.</h2><p className="home-pi-name"><a href="/kanatzidis-demo/people/mercouri-kanatzidis">Mercouri G. Kanatzidis</a><span>Charles E. and Emma H. Morrison Professor of Chemistry</span></p><p>Our group brings together graduate students, postdoctoral researchers, visiting scholars and undergraduates.</p><div className="profile-actions"><a className="text-link dark-link" href="/kanatzidis-demo/people">Group directory →</a><a className="text-link dark-link" href="/kanatzidis-demo/people/mercouri-kanatzidis">Meet Mercouri →</a></div><a className="text-link dark-link" href="/kanatzidis-demo/people/alumni">Explore the alumni archive →</a></div></div></section>
<section className="section news-section home-news" id="news"><div className="shell"><div className="section-heading news-heading"><div><p className="eyebrow dark"><span aria-hidden="true"/>From the group</p><h2>News & recognition</h2></div><a className="text-link dark-link" href="/kanatzidis-demo/news">View all news →</a></div><div className="home-news-layout"><NewsSpotlight/><LatestNews/></div></div></section>
<section className="section contact-section" id="contact"><div className="shell contact-panel"><div><p className="eyebrow light"><span aria-hidden="true"/>Research opportunities</p><h2>Join our research community.</h2></div><div className="contact-copy"><p>Learn about undergraduate research, explore our scientific directions, or get in touch about collaboration.</p><a className="button button-accent" href="/kanatzidis-demo/contact">Contact & opportunities <span aria-hidden="true">↗</span></a></div></div></section>
</main><SiteFooter/></>}
