"use client";
import { useEffect, useState, type FormEvent } from "react";
import { PublicationJournal, publicationJournalSearchText } from "../components/PublicationJournal";
import { PublicationTitle, publicationMatches } from "../components/PublicationText";
import { Citation } from "../components/PaperList";
import papers from "../data/publications.json";
import { Page, SourceLink } from "../components/Content";
type Query={q?:string;year?:string;page?:string};
export default function PublicationArchive(){
 const [query,setQuery]=useState<Query>({});
 useEffect(()=>{const read=()=>{const params=new URLSearchParams(window.location.search);setQuery({q:params.get("q")??"",year:params.get("year")??"all",page:params.get("page")??"1"});};read();window.addEventListener("popstate",read);return()=>window.removeEventListener("popstate",read);},[]);
 const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget);const next={q:String(data.get("q")??""),year:String(data.get("year")??"all"),page:"1"};setQuery(next);window.history.pushState(null,"",`/kanatzidis-demo/publications/?${new URLSearchParams(next)}#results`);};
const q=(query.q??"").trim().slice(0,200);const year=query.year??"all";const years=[...new Set(papers.map(p=>p.year))];const matches=papers.filter(p=>(year==='all'||String(p.year)===year)&&(!q||publicationMatches(p.id,`${p.citation} ${publicationJournalSearchText(p.id)}`,q)));const perPage=25;const totalPages=Math.max(1,Math.ceil(matches.length/perPage));const page=Math.max(1,Math.min(Number.parseInt(query.page??'1',10)||1,totalPages));const visible=matches.slice((page-1)*perPage,page*perPage);const pageHref=(n:number)=>`/kanatzidis-demo/publications/?${new URLSearchParams({q,year,page:String(n)})}#results`;
 return <Page active="publications" eyebrow="Publications" title="Publications" description="A publication archive spanning materials discovery, energy conversion, optical properties and radiation detection."><section className="section publication-archive"><div className="shell"><form key={`${query.q}-${query.year}`} onSubmit={submit} className="publication-filters" action="/kanatzidis-demo/publications" method="get"><label>Search publications<input type="search" name="q" defaultValue={q} placeholder="Title, author, journal, material or DOI"/></label><label>Year<select name="year" defaultValue={year}><option value="all">All years</option>{years.map(y=><option key={y} value={y}>{y}</option>)}</select></label><button className="button button-primary" type="submit">Search</button><a href="/kanatzidis-demo/publications" className="text-link dark-link">Reset</a></form><div className="results-heading" id="results"><p>{matches.length.toLocaleString('en-US')} {matches.length===1?'publication':'publications'}{q&&<> matching “{q}”</>}</p><p>{matches.length>0?`${(page-1)*perPage+1}–${Math.min(page*perPage,matches.length)} of ${matches.length.toLocaleString("en-US")}`:"0 results"}</p></div>{visible.length>0?<div className="paper-list">{visible.map(p=><article className="paper-row" key={p.id}><span className="paper-year">{p.year}</span><div><h2>{p.doi?<a href={`https://doi.org/${p.doi}`}><PublicationTitle id={p.id} text={p.title}/> ↗</a>:<PublicationTitle id={p.id} text={p.title}/>}</h2><PublicationJournal id={p.id}/><Citation text={p.citation} publicationId={p.id}/>{p.doi&&<a className="doi-link" href={`https://doi.org/${p.doi}`}>DOI: {p.doi}</a>}</div></article>)}</div>:<div className="empty-state"><h2>No matching publications</h2><p>Try another author, material or year.</p><a href="/kanatzidis-demo/publications">Show all publications →</a></div>}<nav className="pagination" aria-label="Publication pages">{page>1?<a href={pageHref(page-1)}>← Previous</a>:<span/>}<span>{page} / {totalPages}</span>{page<totalPages?<a href={pageHref(page+1)}>Next →</a>:<span/>}</nav><p className="source-note">Journal details follow the group archive, supplemented by verified DOI records where available. Full citations retain the original archive text. {papers.length.toLocaleString('en-US')} records are indexed here. <SourceLink path="publications.html">Complete original publication list & patents</SourceLink> · <SourceLink path="Publication%20List.pdf">Publication list (PDF)</SourceLink></p></div></section></Page>;
}
